services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "std_2076_course_work"
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql:db
