# Generated by Django 4.1.9 on 2023-06-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_work.category')),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount_fixed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percent', models.FloatField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_work.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('notes', models.TextField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('payment_complete', models.BooleanField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(choices=[('P', 'pickup'), ('O', 'online')], max_length=1)),
                ('order_status', models.CharField(choices=[('N', 'created'), ('A', 'awaiting_payment'), ('C', 'collecting'), ('D', 'delivering'), ('F', 'done'), ('X', 'cancelled')], max_length=1)),
                ('delivery_method', models.CharField(choices=[('P', 'Pickup'), ('C', 'Courier')], max_length=1)),
                ('delivery_address', models.TextField()),
                ('items', models.ManyToManyField(to='course_work.item')),
                ('used_promocode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course_work.promocode')),
            ],
        ),
    ]
