# Generated by Django 4.1.9 on 2023-06-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
