# Generated by Django 4.1.9 on 2023-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0008_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='used_promocode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
