# Generated by Django 4.1.9 on 2023-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0009_alter_order_used_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.FloatField(blank=True, max_length=1, null=True),
        ),
    ]
