# Generated by Django 4.1.9 on 2023-07-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0010_alter_promocode_discount_fixed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
