# Generated by Django 4.1.9 on 2023-07-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0011_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
