# Generated by Django 4.1.9 on 2023-07-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_work', '0012_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('notes', models.TextField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('used_promocode', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(choices=[('P', 'pickup'), ('O', 'online')], max_length=1)),
                ('delivery_method', models.CharField(choices=[('P', 'Pickup'), ('C', 'Courier')], max_length=1)),
                ('delivery_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_work.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_work.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='course_work.OrderItem', to='course_work.item'),
        ),
    ]
